name: server
version: 0.1.0.0
github: "storm-framework/voltron"
license: BSD3
author: "Ranjit Jhala and Nico Lehmann"
maintainer: "rjhala@eng.ucsd.edu"
copyright: "2020 Ranjit Jhala"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/storm-framework/voltron>

dependencies:
  - aeson
    # - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - frankie
  - storm
  - mtl
  - mustache
  - cryptonite
  - persistent
  - persistent-template
  - persistent-sqlite
  - text
  - transformers
  - containers
  - unordered-containers
  - monad-time
  - resource-pool
  - transformers-base
  - monad-control
  - monad-logger
  - mime-types
  - filepath
  - directory
  - cmdargs
  - time
  - network
  - scrypt
  - memory
  - MonadRandom
  - liquid-base
  - liquidhaskell >= 0.8.10

library:
  source-dirs: src
  # ghc-options: -fplugin=LiquidHaskell

executables:
  voltron:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - server

tests:
  server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - server
